operator_type: ffno
operator_cfg:
  in_channels:  6
  out_channels: 3
  width:        128
  modes_x:      24
  modes_y:      24
  n_layers:     6

data_dir:   data/processed/oceanwave3d_large
batch_size: 4
lr:         5.0e-4
epochs:     500
output_dir: outputs/ffno_large

hpc:
  distributed:     true
  n_nodes:         8
  gpus_per_node:   4
  mixed_precision: true
